### ISSUE TITLE
Build with the latest Tarantool version

### ISSUE THREAD

**Issue by zamazan4ik** [tarantool/tpcc#8]
Hi.

Is it possible to build this benchmark with the latest Tarantool version? E.g. where is `tarantool.h`? Would be great if this repo would be tested on the CI as well.

If another way to benchmark Tarantool is recommended instead of `tpcc` - please let me know!

Thanks in advance.

**Comment by DifferentialOrange** [comment]
>  E.g. where is tarantool.h?

You need to install `tarantool-dev` package.

**Comment by zamazan4ik** [comment]
At least in Fedora, `tarantool-devel` package does not provide `tarantool.h` file: https://rpmfind.net/linux/RPM/fedora/36/x86_64/t/tarantool-devel-2.4.2.68-9.fc36.x86_64.html

Also, I did locally `make && make install` on the latest Tarantool version (master branch) and do not see `tarantool.h` installed in the provided `CMAKE_INSTALL_PREFIX/include` path.

**Comment by DifferentialOrange** [comment]
> At least in Fedora, `tarantool-devel` package does not provide `tarantool.h` file: https://rpmfind.net/linux/RPM/fedora/36/x86_64/t/tarantool-devel-2.4.2.68-9.fc36.x86_64.html
> 
> Also, I did locally `make && make install` on the latest Tarantool version (master branch) and do not see `tarantool.h` installed in the provided `CMAKE_INSTALL_PREFIX/include` path.

2.4.2 is outdated. Please, follow installation guide: https://www.tarantool.io/en/download/os-installation/fedora/

**Comment by Totktonada** [comment]
tarantool offers `tarantool/module.h` (in tarantool-devel or tarantool-dev package).

tarantool-c (connector) offers `tarantool.h`.

**Comment by elhimov** [comment]
Runtime and development packages of tarantool-c are available now in tarantool packages repo. As it was mentioned above tarantool.h is a part of tarantool-c development package. However it only fixes step 2 from the [Quick Start Guide](https://github.com/tarantool/tpcc/#quickstart).
